version: "3.3"

networks:
    web:
        driver: bridge
    backend:
        driver: bridge
        internal: true

services:
    caddy: # see https://hub.docker.com/_/caddy
        container_name: caddy
        image: "caddy:latest"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./caddy/data:/data/caddy
            - ../frontend/dist:/dist
        networks:
            - web
            - backend
        environment:
            - DEFAULT_BACKEND_API
        depends_on:
            - fastapi_api
            - quart_api
            - tornado_api

    redis:
        container_name: redis
        image: "redis:latest"
        volumes:
            - ./redis:/data
        networks:
            - backend

    postgres:
        container_name: postgres
        image: postgres:alpine
        networks:
            - backend
        shm_size: "512mb"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    fastapi_api:
        container_name: fastapi_api
        build: ../backend/fastapi_api
        image: fastapi_api
        networks:
            - backend
        env_file:
            - .env
        depends_on:
            - redis
            - postgres

    quart_api:
        container_name: quart_api
        build: ../backend/quart_api
        image: quart_api
        networks:
            - backend
        env_file:
            - .env
        depends_on:
            - redis
            - postgres

    tornado_api:
        container_name: tornado_api
        build: ../backend/tornado_api
        image: tornado_api
        networks:
            - backend
        env_file:
            - .env
        depends_on:
            - redis
            - postgres
