version: "3.3"

networks:
    web:
        driver: bridge
    backend:
        driver: bridge
        internal: true

services:
    caddy: # see https://hub.docker.com/_/caddy
        container_name: caddy
        image: "caddy:latest"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./caddy/data:/data/caddy
            - ../frontend/dist:/dist
        networks:
            - web
            - backend
        environment:
            - DEFAULT_BACKEND_API

    quart_api:
        container_name: quart_api
        build: ../backend/quart_api
        image: quart_api
        networks:
            - backend
        env_file:
            - .env
