[tool.poetry]
name = "tornado_api"
version = "0.1.0"
description = ""
authors = ["André Felipe Dias <andre.dias@pronus.io>"]

[tool.poetry.dependencies]
python = "^3.8"
tornado = "^6.0.4"
python-dotenv = "^0.13.0"
loguru = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-tornado = "^0.8.0"
pytest-cov = "^2.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
