name: Continuous Integration
on: push
jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        name: Continuous Integration
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
            - name: Lint projects
              working-directory: backend
              run: |
                  poetry install
                  poetry run make check
            - name: Test FastAPI app
              working-directory: backend/fastapi_api
              run: |
                  poetry install
                  poetry run make test
            - name: Test Quart app
              working-directory: backend/quart_api
              run: |
                  poetry install
                  poetry run make test
            - name: Test Tornado app
              run: |
                  poetry install
                  poetry run make test
              working-directory: backend/tornado_api
            - name: Test Server
              env:
                  ENV: production
                  DEFAULT_BACKEND_API: fastapi_api
              run: |
                  echo
                  poetry install
                  poetry run make test
              working-directory: server
