name: Continuous Integration
on: push
jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        name: Continuous Integration
        steps:
            - uses: actions/checkout@latest
            - name: Set up Python 3.8
              uses: actions/setup-python@latest
              with:
                  python-version: 3.8
            - name: Install Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
            - name: Lint projects
              run: poetry run make check
              working-directory: backend
            - name: Test FastAPI app
              run: poetry run make test
              working-directory: backend/fastapi_api
            - name: Test Quart app
              run: poetry run make test
              working-directory: backend/quart_api
            - name: Test Tornado app
              run: poetry run make test
              working-directory: backend/tornado_api
            - name: Test Server
              run: poetry run make test
              working-directory: server
