name: Continuous Integration
on: push
jobs:
    lint-and-test-apps:
        runs-on: ubuntu-latest
        name: Lint and Test Applications
        if: false # temporarely disabled to test only the server
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
            - name: Lint projects
              working-directory: backend
              run: |
                  poetry install
                  poetry run make check
            - name: Test FastAPI app
              working-directory: backend/fastapi_api
              run: |
                  poetry install
                  poetry run make test
            - name: Test Quart app
              working-directory: backend/quart_api
              run: |
                  poetry install
                  poetry run make test
            - name: Test Tornado app
              run: |
                  poetry install
                  poetry run make test
              working-directory: backend/tornado_api
    test-server:
        runs-on: ubuntu-latest
        name: Server Smoke Test
        steps:
            - name: Test Server
              run: |
                  echo -e 'ENV=production\nDEFAULT_BACKEND_API=fastapi_api\n' > .env
                  poetry install
                  poetry shell
                  docker-compose -f docker-compose.yml up --build -d
                  docker-compose logs
                  curl --insecure https://localhost/api/hello -v
                  curl --insecure https://localhost/quart_api/hello
                  curl --insecure https://localhost/tornado_api/hello
                  docker-compose down
              working-directory: server
