name: Continuous Integration
on: push
jobs:
    fastapi:
        runs-on: ubuntu-latest
        name: FastAPI Project
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - uses: technote-space/get-diff-action@v2
              with:
                  PREFIX_FILTER: backend/fastapi_api
                  FROM: HEAD^
                  TO: HEAD
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
              if: env.GIT_DIFF
            - name: Testing
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install
                  poetry run make test
              working-directory: backend/fastapi_api
              if: env.GIT_DIFF
    # quart:
    #     runs-on: ubuntu-latest
    #     name: Quart Project
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 2
    #         - name: Set up Python 3.8
    #           uses: actions/setup-python@v2
    #           with:
    #               python-version: 3.8
    #           if: ${{ git diff HEAD^ HEAD --name-only | grep backend/quart_api }}
    #         - name: Testing
    #           run: |
    #               python -m pip install --upgrade pip
    #               pip install poetry
    #               poetry install
    #               poetry run make test
    #           working-directory: backend/quart_api
    #           if: ${{ success() }}
    # tornado:
    #     runs-on: ubuntu-latest
    #     name: Tornado Project
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 2
    #         - name: Set up Python 3.8
    #           uses: actions/setup-python@v2
    #           with:
    #               python-version: 3.8
    #           if: ${{ git diff HEAD^ HEAD --name-only | grep backend/tornado_api }}
    #         - name: Testing
    #           run: |
    #               python -m pip install --upgrade pip
    #               pip install poetry
    #               poetry install
    #               poetry run make test
    #           working-directory: backend/tornado_api
    #           if: ${{ success() }}
    # backend:
    #     runs-on: ubuntu-latest
    #     name: Lint Backend Projects
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 2
    #         - name: Set up Python 3.8
    #           uses: actions/setup-python@v2
    #           with:
    #               python-version: 3.8
    #           if: ${{ git diff HEAD^ HEAD --name-only | grep backend }}
    #         - name: Linting
    #           run: |
    #               python -m pip install --upgrade pip
    #               pip install poetry
    #               poetry install
    #               poetry run make check
    #           working-directory: backend
    #           if: ${{ success() }}
    # test-server:
    #     runs-on: ubuntu-latest
    #     name: Server Smoke Test
    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Set up Python 3.8
    #           uses: actions/setup-python@v2
    #           with:
    #               python-version: 3.8
    #         - name: Test Server
    #           run: |
    #               python -m pip install --upgrade pip
    #               pip install poetry
    #               echo -e 'ENV=production\nDEFAULT_BACKEND_API=fastapi_api\n' > .env
    #               poetry install
    #               poetry run make test
